version: '2'

services:
    web:
        image: weihoop/nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code/nginx:/data/www
            - ./logs/nginx:/var/log/nginx
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - lntrm-network
        depends_on:
            - tomcat
            - redis
            - mysql
    tomcat:
        image: weihoop/tomcat:latest
        volumes:
            - ./code/tomcat:/usr/local/tomcat/webapps
            - ./logs/tomcat:/usr/local/tomcat/logs
        networks:
            - lntrm-network
    redis:
        image: weihoop/redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./dbs/redis:/data
            - ./logs/redis:/var/log/redis
        networks:
            - lntrm-network
    mysql:
        image: weihoop/mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./dbs/mysql:/data/db
            - ./logs/mysql:/data/logs
        environment:
            - MYSQL_ROOT_PASSWORD=RootDocker123
        networks:
            - lntrm-network

networks:
    lntrm-network:
        driver: bridge
