version: '2'

services:
    web:
        image: weihoop/nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code/nginx:/data/www
            - ./logs/nginx:/var/log/nginx
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - lnt-network
    tomcat:
        image: weihoop/tomcat:latest
        volumes:
            - ./code/tomcat:/usr/local/tomcat/webapps
            - ./logs/tomcat:/usr/local/tomcat/logs
        networks:
            - lnt-network

networks:
    lnt-network:
        driver: bridge
