version: '2'

services:
    web:
        image: weihoop/nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/data/www
            - ./logs/nginx:/var/log/nginx
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - lnmp-network
    php:
        image: weihoop/php-fpm:latest
        volumes:
            - ./code:/data/www
            - ./logs/php-fpm:/var/log/php-fpm
            - ./conf/www.conf:/etc/php-fpm.d/www.conf
            - ./conf/php-fpm.conf:/etc/php-fpm.conf
        networks:
            - lnmp-network
    mysql:
        image: weihoop/mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./dbs/mysql:/data/db
            - ./logs/mysql:/data/logs
        environment:
            - MYSQL_ROOT_PASSWORD=RootDocker123
        networks:
            - lnmp-network

networks:
    lnmp-network:
        driver: bridge
